import { useState } from 'react';
import { generatePrenatalPlan } from '@/services/geminiService';
import { Baby, Loader2, HeartPulse, ShieldCheck, Activity } from 'lucide-react';

const PatientPregnancy = () => {
  const [trimester, setTrimester] = useState('1st Trimester (Weeks 1-12)');
  const [conditions, setConditions] = useState('');
  const [plan, setPlan] = useState('');
  const [loading, setLoading] = useState(false);

  const handleGenerate = async () => {
    setLoading(true);
    const result = await generatePrenatalPlan(trimester, conditions);
    setPlan(result);
    setLoading(false);
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h1 className="text-2xl font-bold flex items-center gap-2" style={{ color: '#ec4899' }}>
            <Baby size={28} /> AI Maternal Health Plan
          </h1>
          <p className="text-slate-500 text-sm mt-1">
            Personalised prenatal diet and safe exercise routines generated by clinical AI.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left Column - Input Form */}
        <div className="lg:col-span-1 space-y-4">
          <div className="bg-white p-5 rounded-2xl border shadow-sm" style={{ borderColor: '#fce7f3' }}>
            <div className="mb-4">
              <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">
                Current Stage
              </label>
              <select
                value={trimester}
                onChange={(e) => setTrimester(e.target.value)}
                className="w-full text-sm border p-3 rounded-xl focus:ring-2 focus:ring-pink-400 outline-none"
                style={{ borderColor: '#fbcfe8' }}
              >
                <option>1st Trimester (Weeks 1-12)</option>
                <option>2nd Trimester (Weeks 13-26)</option>
                <option>3rd Trimester (Weeks 27-40)</option>
                <option>Postpartum Recovery</option>
              </select>
            </div>

            <div className="mb-6">
              <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">
                Special Conditions / Symptoms
              </label>
              <textarea
                value={conditions}
                onChange={(e) => setConditions(e.target.value)}
                placeholder="E.g., Morning sickness, Gestational diabetes, Iron deficiency..."
                className="w-full text-sm border p-3 rounded-xl focus:ring-2 focus:ring-pink-400 outline-none min-h-[100px]"
                style={{ borderColor: '#fbcfe8' }}
              />
            </div>

            <button
              onClick={handleGenerate}
              disabled={loading}
              className="w-full flex items-center justify-center gap-2 py-3 rounded-xl font-bold text-white transition-all hover:opacity-90 disabled:opacity-50"
              style={{ background: '#ec4899', boxShadow: '0 4px 14px 0 rgba(236, 72, 153, 0.39)' }}
            >
              {loading ? <Loader2 className="animate-spin" size={20} /> : <HeartPulse size={20} />}
              {loading ? 'Consulting AI...' : 'Generate Plan'}
            </button>
          </div>
          
          <div className="bg-pink-50 p-4 rounded-xl border border-pink-100 flex gap-3 text-pink-800 text-sm">
             <ShieldCheck className="shrink-0" />
             <p>This plan is AI-generated for general guidance. Always consult your OB-GYN before significantly changing your diet or exercise routine.</p>
          </div>
        </div>

        {/* Right Column - Results Display */}
        <div className="lg:col-span-2">
          {plan ? (
            <div className="bg-white rounded-2xl border border-slate-200 overflow-hidden shadow-sm h-full flex flex-col">
              <div className="bg-gradient-to-r from-pink-500 to-rose-400 p-4 text-white">
                <h3 className="font-bold flex items-center gap-2">
                  <Activity size={18} /> Your Personalized Routine
                </h3>
              </div>
              <div className="p-6 overflow-y-auto" style={{ maxHeight: '600px' }}>
                <div className="space-y-4 text-slate-700">
                  {plan.split('\n').map((line, i) => {
                    if (line.startsWith('###')) {
                      return <h4 key={i} className="text-lg font-black text-slate-800 mt-6 mb-2 border-b pb-2">{line.replace('###', '').trim()}</h4>;
                    }
                    if (line.startsWith('-') || line.startsWith('*')) {
                      return <li key={i} className="ml-4 mb-1 text-sm">{line.substring(1).trim()}</li>;
                    }
                    if (line.trim() === '') return null;
                    return <p key={i} className="text-sm">{line}</p>;
                  })}
                </div>
              </div>
            </div>
          ) : (
             <div className="bg-slate-50 border border-slate-200 border-dashed rounded-2xl h-full min-h-[400px] flex flex-col items-center justify-center text-slate-400 p-8 text-center">
                 <Baby size={64} className="mb-4 text-pink-200" />
                 <h3 className="text-lg font-bold text-slate-600 mb-2">Let the AI assist your journey</h3>
                 <p className="text-sm">Select your current trimester and list any symptoms. The AI will instantly build a highly-safe and optimized prenatal guide.</p>
             </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default PatientPregnancy;
